/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerdefender;

import org.junit.jupiter.api.Test;

import towerdefender.engine.Window;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        
        assertNotNull(Window.get(), "app should have a greeting");
    }
}
