/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerdefender;

import org.junit.jupiter.api.Test;
import org.lwjgl.opengl.GL;

import towerdefender.gfx.Shader;

import static org.junit.jupiter.api.Assertions.*;

import static org.lwjgl.opengl.GL30.*;

import java.util.Map;

class AppTest {
    @Test void sourcesCompile(){
        
    }
}
