/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerdefender;

import towerdefender.engine.Window;
import towerdefender.gfx.Renderer;
import towerdefender.scene.Scene;

import static org.lwjgl.glfw.GLFW.glfwGetTime;
import static org.lwjgl.glfw.GLFW.glfwSetWindowTitle;

//contains the game loop
public class Game {

    Renderer renderer;
    public static void main(String[] args) {
        new Game().run();
    }
    private void init(){
        Window.init("blank", 1000, 1000);
        renderer = new Renderer();
        Scene.changeScene(0);
    }
    private void loop(){
        float startTime = (float)glfwGetTime();
        float endTime;
        float deltaTime = -1.0f;

        
        int counter = 0;

        while(!Window.shouldClose()){
            Window.pollEvents();

            renderer.render();
            if(deltaTime >= 0)
                Scene.getCurrentScene().update(deltaTime);
            
            Window.update();

            endTime = (float)glfwGetTime();
            deltaTime = endTime - startTime;
            startTime = endTime;
            counter++;
            if(counter >= 60){
                glfwSetWindowTitle(Window.getHandle(), "|TowerDefender| FPS:"+(1.0f/deltaTime)+" ms:"+(deltaTime*1000));
                counter = 0;
            }
        }
    }
    private void cleanup(){
        Window.cleanup();
        renderer.cleanup();
        Scene.getCurrentScene().cleanup();
    }

    public void run(){
        init();
        loop();
        cleanup();
    }
    
}
