/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerdefender;

import towerdefender.engine.ImGuiLayer;
import towerdefender.engine.Window;
import towerdefender.gfx.Renderer;
import towerdefender.gfx.Shader;
import towerdefender.scene.Scene;
import towerdefender.scene.TutorialScene;

import static org.lwjgl.glfw.GLFW.glfwGetTime;

//contains the game loop
public class Game {

    Renderer renderer;

    public static void main(String[] args) {

        new Game().run();
    }

    private void init() {

        Window.init("blank", 1000, 1000);
        renderer = new Renderer();
        Scene.changeScene(new TutorialScene());

        ImGuiLayer.init();
    }

    private void loop() {
        float startTime = (float) glfwGetTime();
        float endTime;
        float deltaTime = -1.0f;

        Shader defaultS = new Shader("DefaultColor.glsl");

        while (!Window.shouldClose()) {

            // *time management
            ImGuiLayer.currentTime = (float) glfwGetTime();

            endTime = (float) glfwGetTime();
            deltaTime = endTime - startTime;
            startTime = endTime;

            // *render game */
            renderer.clearBuffer();
            Renderer.bindShader(defaultS);
            
            Scene.getCurrentScene().update(deltaTime);

            // *render imgui */
            ImGuiLayer.startRender();
            ImGuiLayer.update(deltaTime);
            ImGuiLayer.endRender();

            Window.update();

        }
    }

    private void cleanup() {
        Window.cleanup();
        renderer.cleanup();
        Scene.getCurrentScene().cleanup();

        ImGuiLayer.cleanup();
    }

    public void run() {
        init();
        loop();
        cleanup();
    }

}
