/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerdefender;

import towerdefender.engine.Window;
import towerdefender.gfx.Renderer;
import towerdefender.gfx.Shader;
import towerdefender.scene.Scene;

import static org.lwjgl.glfw.GLFW.glfwGetTime;

public class Main {

    public static float timeStarted = System.nanoTime();
    public static float getTime(){return (float)((System.nanoTime() - timeStarted) * 1E-9);}

    Renderer renderer;

    public static void main(String[] args) {
        new Main().run();
    }
    private void init(){
        Window.init("blank", 1000, 1000);
        renderer = new Renderer();
        Scene.changeScene(0);
    }
    private void loop(){
        float startTime = (float)glfwGetTime();
        float endTime;
        float deltaTime = -1.0f;



        while(!Window.shouldClose()){
            Window.pollEvents();

            renderer.render();
            if(deltaTime >= 0)
                Scene.getCurrentScene().update(deltaTime);
            
            Window.update();

            endTime = (float)glfwGetTime();
            deltaTime = endTime - startTime;
            startTime = endTime;
        }
    }
    private void cleanup(){
        Window.cleanup();
        renderer.cleanup();
        Scene.getCurrentScene().cleanup();
    }
    //!delta time may not work propory. fix later
    public void run(){
        init();
        loop();
        cleanup();
    }
    
}
