/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package towerdefender;

import towerdefender.engine.Window;
import towerdefender.gfx.Renderer;
import towerdefender.scene.Scene;


public class Main {

    public static float timeStarted = System.nanoTime();
    public static float getTime(){return (float)((System.nanoTime() - timeStarted) * 1E-9);}

    public static void main(String[] args) {
        new Main().run();
    }

    public Main(){
        Window.init("blank", 1000, 1000);
        Renderer.init();
        Scene.changeScene(0);
    }

    //!delta time may not work propory. fix later
    public void run(){

        float startTime = Main.getTime();
        float endTime;
        float deltaTime = -1.0f;

        while(!Window.shouldClose()){
            Window.pollEvents();

            Renderer.render();
            if(deltaTime >= 0)
                Scene.updateCurrentScene(deltaTime);
            
            Window.update();

            endTime = Main.getTime();
            deltaTime = endTime - startTime;
            startTime = endTime;
        }
        cleanup();
    }
    public void cleanup(){
        Window.cleanup();
        Renderer.cleanup();
        Scene.getCurrentScene().cleanup();
    }
}
